### ISSUE TITLE
Blocks not configurable

### ISSUE THREAD

**Issue by hieyou1** [nathanfranke/blockshuffle#1]
Hello,

Great plugin! I'd love if the blocks that get randomly chosen were configurable for a more comprehensive difficulty setting.

Thanks!
hieyou1

**Comment by nathanfranke** [comment]
You can configure them in config.yml. Do you mean more difficulty settings?

**Comment by nathanfranke** [comment]
[Updates available in 1.1](https://github.com/nathanfranke/blockshuffle/releases/tag/1.1)

You may need to delete and regenerate your config.
